db/urls.py
from django.contrib import admin
from django.contrib.admindocs import views
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.HracDetailView.as_view(), name='hrac')
]

movies/models.py
from django.db import models


# Create your models here.

class Hrac(models.Model):
    name = models.CharField(max_length=50,
                            verbose_name='Jméno hráče',
                            help_text='Zadej jméno hráče', )

    country = models.CharField(max_length=50,
                               verbose_name='Národnost',
                               help_text='Zadej národnost hráče', )

    born = models.DateField(verbose_name='Datum narození',
                            help_text='Zadejte, prosím, datum ve formátu: <em>den.měsíc.rok</em>', )

    class Meta:
        verbose_name = 'Hráč'
        verbose_name_plural = 'Hráči'
        ordering = ['name']

    def __str__(self):
        return self.name


class Tym(models.Model):
    name = models.CharField(max_length=50,
                            unique=True,
                            verbose_name='Název týmu',
                            help_text='Zadej název týmu', )

    player = models.ManyToManyField(Hrac,
                                    verbose_name='Zadej hráče',
                                    help_text='Zadej jméno hráče',
                                    )

    class Meta:
        verbose_name = 'Tým'
        verbose_name_plural = 'Týmy'
        ordering = ['name']

    def __str__(self):
        return self.name

movies/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from movies.models import Hrac


class HracDetailView(DetailView):
    model = Hrac
    context_object_name = 'hrac_detail'
    template_name = 'hrac.html'


def index(request):
    popular_players = Hrac.objects.order_by('name')

    context = {
        'popular_players': popular_players,
    }
    return render(request, "index.html", context=context)

movies/templates/base.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Basketbalisté {% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<main>{% block content %} {% endblock %}</main>

</body>
</html>

movies/templates/hrac.html
{% extends "base.html" %}
{% block content %}
    <div style='background-image: url("https://clutchpoints.com/_next/image?url=https%3A%2F%2Fwp.clutchpoints.com%2Fwp-content%2Fuploads%2F2023%2F02%2FThumbnail0.5x-2.png&w=1920&q=75");
  background-repeat: no-repeat;
    background-size: 100%;
        height: 100vh'>
        <h1 class="text-center fs-1 text-white pt-4">{{ hrac_detail.name }}</h1>
        <div class="text-center fs-4 text-white pt-4">
            <p>Narozen: {{ hrac_detail.born }}, {{ hrac_detail.country }}</p>
            {% for tym in hrac_detail.tym_set.all%}
                <p>{{ tym.name }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

movies/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div style='background-image: url("https://clutchpoints.com/_next/image?url=https%3A%2F%2Fwp.clutchpoints.com%2Fwp-content%2Fuploads%2F2023%2F02%2FThumbnail0.5x-2.png&w=1920&q=75");
  background-repeat: no-repeat;
    background-size: 100%;
        height: 100vh'>
        <h1 class="text-center fs-1 text-white pt-4">Basketbalisté</h1>
        {% for popular_player in popular_players %}
            <div class="text-center text-white fs-3">
                <a href="{% url 'hrac' popular_player.pk %}"style="color:white!important">{{ popular_player.name }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}